# Base configs
baseurl: "https://frapgadz.github.io/photography/"
image_fulls_loc: "/images/fulls"
image_thumbs_loc: "/images/thumbs"
google_analytics: ""

# UI configs
title: "Photography by Jack Denny (CrimesAgainstPhotography)"
subtitle: "Shots fired"
author: "Jack Denny"
header:
 title: "Photography"
 subtitle: "by Jack Denny"
footer:
 name: "Hey there, my name is Jack"
 bio: "I wish I was a legitimate photographer, but until then I will spray and pray"
 github: "Want a website like this for yourself for free? Just <a href=\"https://github.com/ramswaroop/photography\">fork me on github</a> ;)"
web_design: "AJ"
social_urls:
  facebook: ""
  twitter: ""
  instagram: "https://www.instagram.com/crimesagainstphotography/"
  dribbble: ""
  linkedin: ""
  github: "https://www.github.com/frapgadz"
